import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Pedido() {
  return (
    <div className={styles.container}>
      <Head>
        <title>UBAffets | Pedido</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Pedido</h1>
      <Link href="/">Volver a la página principal</Link>
    </div>
  )
}