@startuml

UI -> Cliente: agregarProductoAlPedido(pancho: Producto, cantidad: int)

note right: Por medio de las cookies el buffet siempre puede saber qué cliente le habla

Cliente -> Buffet: agregarProductoAlPedido(pedido: Pedido, pancho: Producto, cantidad: int)
Buffet -> Almacen: retirarProducto(pancho, cantidad)
Buffet --> Cliente: Se le agrega el producto al pedido

note right: En caso de haber se descuenta del stock

Almacen --> Buffet: true

UI -> Cliente: comprar()
Cliente -> Buffet: nuevaCompra(pedido: Pedido)
Buffet-> Compra: new(Pedido)
Compra --> Buffet: compra
Buffet -> GeneradorDeCodigo: generarCodigo()
GeneradorDeCodigo --> Buffet: codigo
Buffet --> Cliente: compra, codigo

note right: el cliente guarda la compra con su codigo

@enduml