@startuml
class Cliente {
    - saldo: Dinero
    - pedido: Pedido 
    - historialDeCompras: List<Compra>
    - buffetIngresado: Buffet
    + ingresarBuffet(Buffet buffet)
    + cargarSaldo(monto: Dinero)
    + agregarAlPedido(String nombreProducto, int cantidad)
    + cantidadDeProductos(): int
    + valorDelPedido(): Dinero
    + comprar()
    + historialDeCompras(): List<Compra>
    + confirmarCompraDelPedido()
}

class Producto {
    - precio: Dinero 
    - nombre: String
    - cantidad: int
    + precioSegunCantidad(): Dinero
    + retirar(cantidad: int): Producto
}

class Compra {
    - pedido: Pedido
    - fecha: LocalDateTime
    - id_compra: int
}

class Dinero {
    - monto: BigDecimal
    + plus(otro: Dinero): Dinero
    + minus(otro: Dinero): Dinero
    + compareTo(otro: Dinero): int
    + multiply(int cantidad): Dinero
}

class Almacen{
    -inventario: Map<nombre: String, Producto>
    +estaRegistrado(String nombreDelProducto): boolean
    +hayStock(String nombreDelProducto): boolean
    +retirarProducto(String nombreDelProducto, int cantidadARetirar, Pedido pedido)
    +actualizarPrecio(String nombreDelProducto, Dinero nuevoPrecio)
    +actulizarStock(String nombreDelProducto, int nuevoStock)
}

class Pedido {
    - productos: Map<String, Producto>
    + agregar(Producto producto)
    + cantidadDeProductos(): int
    + precio(): Dinero
}

class Buffet {
    -almacen: Almacen
    -comprasRegistradas: List<Compra>
    -ids_compras: int
    +registrarProducto(Producto producto)
    +actualizarPrecio(String nombreDelProducto, Dinero nuevoPrecio)
    +ingresarStock(String nombreDelProducto, int nuevoStock)
    +hayStock(String nombreDelProducto): boolean
    +agregarAlPedido(String nombreProducto, int cantidad, Pedido pedido)
    +registrarCompra(Pedido pedido): Compra
    +comprasRegistradas(): List<Compra> comprasRegistradas
}

Cliente o-right- "1" Buffet
Cliente o-- "1" Pedido
Cliente o-- "*" Compra
Cliente o- "1" Dinero

Producto o-- "1" Dinero

Pedido o- Producto

Almacen o-- "*" Producto
'Almacen ..> Dinero
'Almacen ..> Pedido

Buffet *-- "1" Almacen
Buffet o-- "*" Compra
'Buffet ..> Dinero
'Buffet ..> Pedido

@enduml
